feria/urls.py
from django.urls import path

import feria.views as views

urlpatterns = [
    path('', views.index),
    path('login/', views.login_view),
    path('logout/', views.logout_view),
    path('tablero/', views.board),
    path('entregas/', views.epics),
    path('entregas/nueva/', views.new_epic),
    path('entregas/<int:epic_id>/', views.epic_detail),
    path('hdu/<int:feature_id>/', views.hdu),
    path('foros/', views.forum),
    path('foros/<int:forum_id>/', views.forum_detail),
    path('foros/mensaje/<int:message_id>/', views.message_detail),
    path('archivos/', views.archivos)
]

pgproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

import pgproject.settings as settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feria.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feria/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Team(models.Model):
    user = models.ManyToManyField(User)
    event = models.ForeignKey('Event', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    logo = models.ImageField(upload_to='feria/team/logos/', null=True)


class Event(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    logo = models.ImageField(upload_to='feria/event/logos/', null=True)


class Forum(models.Model):
    team = models.OneToOneField('Team', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200)
    public = models.BooleanField()


class Message(models.Model):
    class Meta:
        ordering = ['-updated_at']

    forum = models.ForeignKey('Forum', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Answer(models.Model):
    class Meta:
        ordering = ['-updated_at']

    message = models.ForeignKey('Message', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Epic(models.Model):
    class Meta:
        ordering = ['id']

    team = models.ForeignKey('Team', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Feature(models.Model):
    class Meta:
        ordering = ['-updated_at']

    epic = models.ForeignKey('Epic', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    criteria = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Task(models.Model):
    BACKLOG = 0
    ONGOING = 1
    DONE = 2
    ACEPTED = 3
    STATE_CHOICES = (
        (BACKLOG, 'No Iniciada'),
        (ONGOING, 'En Desarrollo'),
        (DONE, 'Terminada'),
        (ACEPTED, 'Aceptada'))

    feature = models.ForeignKey('Feature', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200)
    state = models.PositiveSmallIntegerField(
        choices=STATE_CHOICES,
        default=BACKLOG)
    description = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

feria/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

import feria.models as models
import feria.security as security


# Create your views here.
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET.get('next', '/'))
        else:
            return render(
                request,
                'feria/login.html',
                {'error': 'Nombre de Usuario o contraseña incorrectos'})
    return render(request, 'feria/login.html')


def logout_view(request):
    logout(request)
    return redirect('/login/')


@login_required
def index(request):
    return render(request, 'feria/index.html', {'dashboard': 'active'})


@login_required
def board(request):
    if request.method == 'POST':
        feature_id = request.POST.get('feature_id')
        feature = models.Feature.objects.get(pk=feature_id)
        name = request.POST.get('name')
        description = request.POST.get('description')
        if request.POST.get('task_id'):
            pk = request.POST.get('task_id')
            state = request.POST.get('state')
            models.Task.objects.filter(id=pk).update(
                feature=feature,
                name=name,
                description=description,
                state=state)
        else:
            new_task = models.Task(
                feature=feature,
                name=name,
                description=description,)
            new_task.save()
    team = request.user.team_set.all()[0]
    tasks = models.Task.objects.filter(feature__epic__team=team)
    backlog = tasks.filter(state=models.Task.BACKLOG)
    in_progress = tasks.filter(state=models.Task.ONGOING)
    done = tasks.filter(state=models.Task.DONE)
    finished = tasks.filter(state=models.Task.ACEPTED)
    return render(
        request,
        'feria/board.html',
        {
            'backlog': backlog,
            'in_progress': in_progress,
            'done': done,
            'finished': finished,
            'board': 'active',
        })


@login_required
def epics(request):
    if request.GET.get('team_id'):
        if not security.user_team(request, request.GET.get('team_id')):
            return redirect('/entregas/')
        epics_list = models.Epic.objects.filter(
            team=models.Team.objects.get(pk=request.GET.get('team_id')))
        return render(request, 'feria/epics/epics.html', {
            'epics': 'active',
            'team_id': int(request.GET.get('team_id')),
            'epics_list': epics_list,
        })
    else:
        return render(request, 'feria/epics/all_epics.html', {
            'all_epics': 'active',
        })


@login_required
def new_epic(request):
    if not security.user_team(request, request.GET.get('team_id')):
        return redirect('/entregas/')
    if request.method == 'POST':
        new_epic = models.Epic(
            team=models.Team.objects.get(pk=request.GET.get('team_id')),
            name=request.POST.get('name'),
            description=request.POST.get('description'))
        new_epic.save()
    return render(request, 'feria/epics/new_epic.html', {
        'team_id': int(request.GET.get('team_id')),
        'new_epic': 'active',
    })


@login_required
def epic_detail(request, epic_id):
    if not security.user_epic(request, epic_id):
        return redirect('/entregas/')
    if request.method == 'POST':
        e = models.Epic.objects.get(pk=request.POST.get('id'))
        e.name = request.POST.get('name')
        e.description = request.POST.get('description')
        e.save()
    return render(request, 'feria/epics/epic_detail.html', {
            'e': models.Epic.objects.get(pk=epic_id),
        })


@login_required
def hdu(request, feature_id):
    if not security.user_feature(request, feature_id):
        return redirect('/entregas/')
    if request.method == 'POST':
        f = models.Feature.objects.get(pk=request.POST.get('id'))
        f.name = request.POST.get('name')
        f.description = request.POST.get('description')
        f.criteria = request.POST.get('criteria')
        f.save()
    return render(request, 'feria/features/hdu.html')


@login_required
def forum(request):
    return render(
        request,
        'feria/forum.html', {
            'forum': 'active',
            'user_forums':
                list(models.Forum.objects.filter(public=True))
                + list(t.forum for t in request.user.team_set.all())
        })


@login_required
def forum_detail(request, forum_id):
    if not security.user_forum(request, forum_id):
        return redirect('/foros/')
    f = models.Forum.objects.get(pk=forum_id)
    if request.method == 'POST':
        new_message = models.Message(
            forum=f,
            user=request.user,
            title=request.POST['title'],
            content=request.POST['nessage_text'])
        new_message.save()
    return render(
        request,
        'feria/forum_detail.html', {
            'forum': 'active',
            'f': f,
        })


@login_required
def message_detail(request, message_id):
    message = models.Message.objects.get(pk=message_id)
    if not security.user_forum(request, message.forum.id):
        return redirect('/foros/')
    if request.method == 'POST':
        new_answer = models.Answer(
            message=message,
            user=request.user,
            content=request.POST['nessage_text'],
            )
        new_answer.save()
    return render(
        request,
        'feria/message_detail.html', {
            'forum': 'active',
            'm': message,
            'answers': message.answer_set.all().order_by('created_at')
        })


@login_required
def archivos(request):
    return render(request, 'feria/filesystem.html', {'filesystem': 'active'})

feria/templates/feria/epic_detail.html
{% extends 'feria/base.html' %}
{% load static %}

{% block content %}
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4>
                <span class="text-semibold"><a href="/entregas/" style="color: black;">Entregas</a></span> - {{ e.name }}
            </h4>
        </div>
    </div>
</div>
<div class="content">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h6><a href="/entregas/{{ e.id }}/">{{ e.name|title }}</a> &#183; <span class="text-muted">{{e.team.name}}</span></h6>
                <div class="heading-elements">
                    <button type="button" class="btn btn-primary heading-btn legitRipple">Editar</button>
                </div>
            </div>
            <div class="panel-body">
                <div class="content" style="padding-bottom: 40px;">{{ e.description|safe }}</div>
                {% if e.feature_set.all %}
                <div class="row">
                    {% for f in e.feature_set.all %}
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h6><a href="/caracteristicas/{{f.id}}/">{{f.name}}</a></h6>
                            </div>
                            <div class="panel-body">
                                {{ f.description|safe }}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

feria/templates/feria/epics.html
{% extends 'feria/base.html' %}
{% load static %}

{% block js %}
<script type="text/javascript" src="{% static 'feria/js/plugins/editors/summernote/summernote.min.js' %}"></script>
<script type="text/javascript" src="{% static 'feria/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script type="text/javascript">

    function activate_form(initial_text) {
        var div = document.createElement('div');
        div.innerHTML = initial_text.trim();

        $('#name-div').hide();
        $('#name-input').show();

        $('#description-div').hide();
        $('#description-input').show();

        $('#button-edit').hide();
        $('#button-save').show();

        $('.summernote').summernote('insertNode', div.firstChild);
    }
</script>
{% endblock %}

{% block content %}
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4>
                <span class="text-semibold"><a href="/entregas/" style="color: black;">Entregas</a></span>
            </h4>
        </div>
    </div>
</div>
<div class="content">
    {% for t in request.user.team_set.all %}
    <div class="row">
        {% for e in t.epic_set.all %}
        <form method="POST">
            {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h6 id="name-div"><a href="/entregas/{{ e.id }}/">{{ e.name }}</a> &#183; <span class="text-muted">{{t.name}}</span></h6>
                    <input type="hidden" name="id" value="{{ e.id }}">
                    <input id="name-input" class="form-control" type="text" name="name" value="{{ e.name }}" style="display: none;">
                    <div class="heading-elements">
                        <button id="button-edit" type="button" class="btn btn-warning heading-btn legitRipple" onclick="activate_form('{{ e.description|safe }}');">Editar</button>
                        <button id="button-save" type="submit" class="btn btn-primary heading-btn legitRipple" style="display: none;">Guardar</button>
                    </div>
                </div>
                <div class="panel-body">
                    <div id="description-div" class="content" style="padding-bottom: 40px;">{{ e.description|safe }}</div>
                    <textarea id="description-input" class="summernote" name="description" style="display: none;"></textarea>
                    {% if e.feature_set.all %}
                    <div class="row">
                        {% for f in e.feature_set.all|slice:":3" %}
                        <div class="col-md-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h6><a href="/caracteristicas/{{f.id}}/">{{f.name}}</a></h6>
                                </div>
                                <div class="panel-body">
                                    {{ f.description|safe }}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </form>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

feria/templates/feria/filesystem.html
{% extends 'feria/base.html' %}
{% load static %}

{% block content %}
<div class="content">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5>Archivos</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="panel panel-flat">
                <div class="panel-heading">Archivo</div>
                <div class="panel-body">
                    <p>Descripcion del archivo</p>
                    <div class="thumbnail">
                        <a href="{% static 'feria/images/placeholder.jpg' %}">
                            <img src="{% static 'feria/images/placeholder.jpg' %}">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

feria/templates/feria/forum.html
{% extends 'feria/base.html' %}
{% load static %}

{% block content %}
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4>
                <span class="text-semibold"><a href="/foros/" style="color: black;">Foros</a></span>
            </h4>
        </div>
    </div>
</div>
<div class="content">
    <div class="row">
        {% for f in user_forums %}
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h6>
                        <a href="/foros/{{ f.id }}/" class="text-bold">{{ f.name|title }}</a>
                    </h6>
                </div>
                <div class="panel-body">
                    {% if f.message_set.all %}
                    <div class="panel panel-plain">
                        <div class="panel-heading">
                            <a href="/foros/mensaje/{{ f.message_set.all.0.id }}/" class="text-semibold">{{ f.message_set.all.0.title }}</a>
                        </div>
                        <div class="panel-body">
                            {{ f.message_set.all.0.content|safe }}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

feria/templates/feria/forum_detail.html
{% extends 'feria/base.html' %}
{% load static %}

{% block js %}
<script type="text/javascript" src="{% static 'feria/js/plugins/editors/summernote/summernote.min.js' %}"></script>
<script type="text/javascript" src="{% static 'feria/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script type="text/javascript">
    $(function() {
        $('.summernote').summernote();
    });

    function activate_form() {
        $('form').show();
    }
</script>
{% endblock %}

{% block content %}
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4>
                <span class="text-semibold">
                    <a href="/foros/" style="color: black;">Foros</a>
                </span> - <a href="/foros/{{ f.id }}/" style="color: black;">{{ f.name }}</a>
            </h4>
        </div>
        <div class="heading-elements">
            <div class="heading-btn-group">
                <button type="button" class="btn btn-primary legitRipple" onclick="activate_form();">Nuevo Mensaje</button>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="row">
        {% for m in f.message_set.all %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h6>
                    <a href="/foros/mensaje/{{ m.id }}/" class="text-bold">{{ m.title }}</a>
                </h6>
            </div>
            <div class="panel-body">
                {{ m.content|safe }}
                {% if m.answer_set.all %}
                <div class="panel panel-plain mt-20">
                    <div class="panel-heading">
                        <span class="text-semibold">{{ m.answer_set.all.0.user.username }}</span><span class="text-muted"> - {{ m.answer_set.all.0.updated_at }}</span>
                    </div>
                    <div class="panel-body">
                        {{ m.answer_set.all.0.content|safe }}
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        <form method="POST" style="display: none;">
            {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <input type="text" class="form-control" name="title" placeholder="Titúlo">
                </div>
                <div class="panel-body">
                    <textarea class="summernote" name="nessage_text"></textarea>
                    <button type="submit" class="btn btn-primary legitRipple">Enviar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

feria/templates/feria/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PG Project Management</title>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="{% static 'feria/css/icons/icomoon/styles.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'feria/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'feria/css/core.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'feria/css/components.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'feria/css/colors.css' %}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script type="text/javascript" src="{% static 'feria/js/plugins/loaders/pace.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'feria/js/core/libraries/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'feria/js/core/libraries/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'feria/js/plugins/loaders/blockui.min.js' %}"></script>
    <!-- /core JS files -->


    <!-- Theme JS files -->
    <script type="text/javascript" src="{% static 'feria/js/core/app.js' %}"></script>

    <script type="text/javascript" src="{% static 'feria/js/plugins/ui/ripple.min.js' %}"></script>
    <!-- /theme JS files -->

</head>

<body class="login-container">

    <!-- Main navbar -->
    <div class="navbar navbar-inverse bg-indigo">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><img src="{% static 'feria/images/logo_light.png' %}" alt="PG Project"></a>

            <ul class="nav navbar-nav pull-right visible-xs-block">
                <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
            </ul>
        </div>

        <div class="navbar-collapse collapse" id="navbar-mobile">
        </div>
    </div>
    <!-- /main navbar -->


    <!-- Page container -->
    <div class="page-container">

        <!-- Page content -->
        <div class="page-content">

            <!-- Main content -->
            <div class="content-wrapper">

                <!-- Content area -->
                <div class="content">

                    <!-- Simple login form -->
                    <form method="POST"> {% csrf_token %}
                        <div class="panel panel-body login-form">
                            <div class="text-center">
                                <div class="icon-object border-slate-300 text-slate-300"><i class="icon-reading"></i></div>
                                <h5 class="content-group">Porfavor inicie sesión <small class="display-block">Ingrese sus credenciales a continuación</small></h5>
                            </div>

                            <div class="form-group has-feedback has-feedback-left">
                                <input type="text" class="form-control" placeholder="Username" name="username">
                                <div class="form-control-feedback">
                                    <i class="icon-user text-muted"></i>
                                </div>
                            </div>

                            <div class="form-group has-feedback has-feedback-left">
                                <input type="password" class="form-control" placeholder="Password" name="password">
                                <div class="form-control-feedback">
                                    <i class="icon-lock2 text-muted"></i>
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn bg-pink-400 btn-block">Iniciar Sesión <i class="icon-circle-right2 position-right"></i></button>
                            </div>

                            <div class="text-center">
                                <a href="login_password_recover.html">Olvido su contraseña?</a>
                            </div>
                        </div>
                    </form>
                    <!-- /simple login form -->


                    <!-- Footer -->
                    <div class="footer text-muted text-center">
                        &copy; 2015. <a href="#">Limitless Web App Kit</a> by <a href="http://themeforest.net/user/Kopyov" target="_blank">Eugene Kopyov</a>
                    </div>
                    <!-- /footer -->

                </div>
                <!-- /content area -->

            </div>
            <!-- /main content -->

        </div>
        <!-- /page content -->

    </div>
    <!-- /page container -->

</body>
</html>